import Head from "next/head";
import styles from "../styles/index.module.css";
import { useSelector } from "react-redux";

export default function Home() {
  const { todos } = useSelector((state) => state.todos);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>Todos State</h2>
      <div className={styles.todosContainer}>
        {todos.length === 0 && <h4> THERE ARE NO TODOS </h4>}
        {todos.map((todo) => (
          <h4 key={todo.id}>{todo.title}</h4>
        ))}
      </div>
    </div>
  );
}
